version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: neuro-beats-backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - FLASK_ENV=production
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SECRET_KEY
    volumes:
      - ./backend/certs:/app/certs:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neuro-beats-frontend
    restart: unless-stopped
    volumes:
      - ./backend/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 